# biochef-hub/.github/workflows/publish-recipes.yml
name: Publish BioChef Recipes
on:
  workflow_call:
    inputs:
      registry_url:
        required: true
        type: string
      recipes:
        required: true
        type: string
      oras_auth:
        required: true
        type: string
    secrets:
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: ieeta-pt/biochef-hub
          path: .hub

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: |
          python -m pip install --upgrade pip
          pip install -r ./.hub/hub/requirements.txt

      - name: Install Emscripten
        run: |
          sudo apt update
          sudo apt install -y cmake python3 python3-pip nodejs npm
          git clone https://github.com/emscripten-core/emsdk.git ./.hub/emsdk
          cd ./.hub/emsdk
          ./emsdk install 4.0.18
          ./emsdk activate 4.0.18

      - name: Validate, Build and Test Recipes
        run: |
          source ./.hub/emsdk/emsdk_env.sh
          python ./.hub/hub/hub.py validate ${{ inputs.recipes }}
          python ./.hub/hub/hub.py build

      - name: Publish to Registry
        env:
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          ORAS_AUTH_BACKED: ${{ inputs.oras_auth }}
        run: python ./.hub/hub/hub.py publish --registry "${{ inputs.registry_url }}"
